### ISSUE TITLE
The big bad Pre-Alpha Testing result Tracker

### ISSUE THREAD

**Issue by Penaz91** [Penaz91/Glitch_Heaven#61]
- [x] Fix Menu bug: If you click on a setting, it doesn't change (Mouse bug)
- [x] Fix Menu bug: If you go to a previous menu, the code might sense the previous click and snowball until  a click on "quit" is detected
- [x] Enhancement:The Player character is missing Inertia: I will have to recode the H-movement anyway
- [x] Enhancement: Make an instructional screen to teach buttons and mechanics
- [x] Fix Saving on MacOS - Crash when saving.
- [x] Fix Chdir on MacOS/Linux - Doesn't detect correct directory
- [x] Fix Mixer Pre-Init Bug on MacOS
- [x] Make Checkpoints look active when activated
- [x] Make Buttons look active when activated
- [x] Make it so you can't set in a "pushing" status if you're not in the "resting" status.
- [x] Fix Loading: Intermissions need to be memorised in the game status or reloaded from the campaign file.
- [ ] Enhancement: Memorize "Last checkpoint" for restoring with SaveGames
- [x] Bug: Seems that if you hit a corner with enough speed, you can cross through it.
- [x] Enhancement: Move Configuration from configparser to JSON, for quicker load and storage of settings.
- [x] Enhancement: Add a way to show a ComicReader instance when the campaign is finished.
- [ ] Enhancement: Make sliding floor edit speed instead of movement? So to keep momentum when jumping off it
- [x] Bug: Collision Detection + Hover Glitch + Going left = Player sprite switching left/right repeatedly
- [x] Bug: Menus don't update when you create the first savegame
- [ ] ...

**Comment by Penaz91** [comment]
Saving/Loading is broken in MacOS because of a bug in TK that doesn't allow for right creation of cocoa classes

**Comment by Penaz91** [comment]
Working on a new save/load system that will be independent from TK

**Comment by Penaz91** [comment]
Added a basic proof-of-concept for the HowTo thingy

**Comment by Penaz91** [comment]
Corner crossing should be solved by the 60Fps update, I think i took care of the pushing matter too.
